# Generated by Django 5.0.6 on 2024-05-20 06:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intrusive", "0003_rename_tag_name_tag_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SideNote",
        ),
    ]
